name: Update K8s Contributions

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-user-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Generate Kubernetes Contributions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run main.go --kubernetes

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/kubernetes_contributions.html
          git commit -m "Update k8s contributions"
          git push
